// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOF13vNixECbdHGiVSOXpaPf5V8gzrAw0',
    appId: '1:743083597128:android:f2e56eca840fa55e2da77d',
    messagingSenderId: '743083597128',
    projectId: 'meetup-d2efb',
    databaseURL: 'https://meetup-d2efb-default-rtdb.firebaseio.com',
    storageBucket: 'meetup-d2efb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxc5kufsYVBQ24pkc-FD6yPC3GA2lzX0s',
    appId: '1:743083597128:ios:37e3972eafbfd0812da77d',
    messagingSenderId: '743083597128',
    projectId: 'meetup-d2efb',
    databaseURL: 'https://meetup-d2efb-default-rtdb.firebaseio.com',
    storageBucket: 'meetup-d2efb.appspot.com',
    iosClientId: '743083597128-l8l7rbspumtrgi5ivue652935rv9f7u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );
}
